kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tiantian/code-server/redis"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-2
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tiantian/code-server/redis"




